"use strict";
/* eslint-disable no-template-curly-in-string */
Object.defineProperty(exports, "__esModule", { value: true });
exports.details = void 0;
var details = function () { return ({
    name: 'VMAF Parameter Optimization',
    description: 'VMAF-aware optimization workflow with intelligent retry logic. Only retries with CQ values that had acceptable VMAF during sweep. Triggers sweep retry when no higher CQ was tested. Includes Bayesian learning, live size monitoring, and clear error messages for impossible scenarios.',
    tags: 'video,vmaf,optimization,quality,learning,retry',
    flowPlugins: [
        {
            name: 'Input File',
            sourceRepo: 'Community',
            pluginName: 'inputFile',
            version: '1.0.0',
            id: 'input1',
            position: { x: 400, y: 100 },
        },
        {
            name: 'Check File Age',
            sourceRepo: 'Local',
            pluginName: 'checkFileAge',
            version: '1.0.0',
            id: 'agecheck1',
            position: { x: 400, y: 200 },
        },
        {
            name: 'Detect GPU Encoder',
            sourceRepo: 'Local',
            pluginName: 'detectGPUEncoder',
            version: '1.0.0',
            id: 'gpu1',
            position: { x: 400, y: 300 },
        },
        {
            name: 'Extract Video Samples',
            sourceRepo: 'Local',
            pluginName: 'extractVideoSamples',
            version: '1.0.0',
            id: 'extract1',
            position: { x: 400, y: 400 },
        },
        {
            name: 'Test Encoding Parameters',
            sourceRepo: 'Local',
            pluginName: 'testEncodingParameters',
            version: '1.0.0',
            id: 'test1',
            position: { x: 400, y: 500 },
        },
        {
            name: 'Calculate VMAF',
            sourceRepo: 'Local',
            pluginName: 'calculateVMAF',
            version: '1.0.0',
            id: 'vmaf1',
            position: { x: 400, y: 600 },
        },
        {
            name: 'Select Best Parameters',
            sourceRepo: 'Local',
            pluginName: 'selectBestParameters',
            version: '1.0.0',
            id: 'select1',
            position: { x: 400, y: 700 },
        },
        {
            name: 'Check CQ Range Retry',
            sourceRepo: 'Local',
            pluginName: 'checkCQRangeRetry',
            version: '1.0.0',
            id: 'retry1',
            position: { x: 400, y: 750 },
        },
        {
            name: 'Learn CQ Range',
            sourceRepo: 'Local',
            pluginName: 'learnCQRange',
            version: '1.0.0',
            id: 'learn1',
            position: { x: 400, y: 800 },
        },
        {
            name: 'Export VMAF Results to CSV',
            sourceRepo: 'Local',
            pluginName: 'exportVMAFResults',
            version: '1.0.0',
            id: 'export1',
            position: { x: 400, y: 850 },
        },
        {
            name: 'Compare File Size Ratio Live',
            sourceRepo: 'Community',
            pluginName: 'compareFileSizeRatioLive',
            version: '1.0.0',
            id: 'sizeCheck1',
            position: { x: 400, y: 900 },
        },
        {
            name: 'VMAF Optimized Transcode',
            sourceRepo: 'Local',
            pluginName: 'vmafOptimizedTranscode',
            version: '1.0.0',
            id: 'transcode1',
            position: { x: 400, y: 950 },
        },
        {
            name: 'Monitor Transcode Retry',
            sourceRepo: 'Local',
            pluginName: 'monitorTranscodeRetry',
            version: '1.0.0',
            id: 'monitorRetry1',
            position: { x: 400, y: 1000 },
        },
        {
            name: 'Replace Original File',
            sourceRepo: 'Community',
            pluginName: 'replaceOriginalFile',
            version: '1.0.0',
            id: 'replace1',
            position: { x: 400, y: 1050 },
        },
    ],
    flowEdges: [
        {
            source: 'input1',
            sourceHandle: '1',
            target: 'agecheck1',
            targetHandle: null,
            id: 'edge0',
        },
        {
            source: 'agecheck1',
            sourceHandle: '1',
            target: 'gpu1',
            targetHandle: null,
            id: 'edge1',
        },
        {
            source: 'gpu1',
            sourceHandle: '1',
            target: 'extract1',
            targetHandle: null,
            id: 'edge2',
        },
        {
            source: 'gpu1',
            sourceHandle: '2',
            target: 'extract1',
            targetHandle: null,
            id: 'edge2b',
        },
        {
            source: 'extract1',
            sourceHandle: '1',
            target: 'test1',
            targetHandle: null,
            id: 'edge3',
        },
        {
            source: 'test1',
            sourceHandle: '1',
            target: 'vmaf1',
            targetHandle: null,
            id: 'edge4',
        },
        {
            source: 'vmaf1',
            sourceHandle: '1',
            target: 'select1',
            targetHandle: null,
            id: 'edge5',
        },
        {
            source: 'select1',
            sourceHandle: '1',
            target: 'retry1',
            targetHandle: null,
            id: 'edge6',
        },
        {
            source: 'select1',
            sourceHandle: '2',
            target: 'retry1',
            targetHandle: null,
            id: 'edge6a',
        },
        {
            source: 'retry1',
            sourceHandle: '1',
            target: 'test1',
            targetHandle: null,
            id: 'edge6b',
        },
        {
            source: 'retry1',
            sourceHandle: '2',
            target: 'learn1',
            targetHandle: null,
            id: 'edge6c',
        },
        {
            source: 'learn1',
            sourceHandle: '1',
            target: 'export1',
            targetHandle: null,
            id: 'edge6d',
        },
        {
            source: 'export1',
            sourceHandle: '1',
            target: 'sizeCheck1',
            targetHandle: null,
            id: 'edge7',
        },
        {
            source: 'sizeCheck1',
            sourceHandle: '1',
            target: 'transcode1',
            targetHandle: null,
            id: 'edge7a',
        },
        {
            source: 'transcode1',
            sourceHandle: '1',
            target: 'monitorRetry1',
            targetHandle: null,
            id: 'edge7b',
        },
        {
            source: 'transcode1',
            sourceHandle: '2',
            target: 'monitorRetry1',
            targetHandle: null,
            id: 'edge7c',
        },
        {
            source: 'monitorRetry1',
            sourceHandle: '1',
            target: 'transcode1',
            targetHandle: null,
            id: 'edge7d',
        },
        {
            source: 'monitorRetry1',
            sourceHandle: '2',
            target: 'replace1',
            targetHandle: null,
            id: 'edge8',
        },
        {
            source: 'monitorRetry1',
            sourceHandle: '3',
            target: 'retry1',
            targetHandle: null,
            id: 'edge8b',
        },
    ],
}); };
exports.details = details;
